branch-defaults:
  deploy:
    environment: prme-env
environment-defaults:
  prme-env:
    branch: null
    repository: null
global:
  application_name: patient-risk-model-explainer-ui
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.7 running on 64bit Amazon Linux 2
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
